name: sipeka
description: A personal finance management app for financial literacy
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.4.1
  path: ^1.9.0

  # OCR & Image Handling - Update ke versi yang mendukung SDK terbaru
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  google_mlkit_text_recognition: ^0.13.1 # Update dari 0.11.0
  google_mlkit_commons: ^0.8.1        # Tambahkan ini secara eksplisit jika perlu

  # State Management & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  
  # Persistence
  csv: ^6.0.0
  share_plus: ^10.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  
  # UI & Charts
  fl_chart: ^0.70.0 # Versi terbaru lebih stabil dengan Flutter 3.x
  percent_indicator: ^4.2.3
  
  # Calculator Logic
  math_expressions: ^2.6.0

  # Utilities
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png" # Sesuaikan dengan nama file logomu
  adaptive_icon_background: "#007AFF" # Warna background (opsional)
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true