// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw0uvnKdQ3NRBjBTO8xIKF0a9as8grySc',
    appId: '1:184071946564:android:4edb8c65f792eed40fd711',
    messagingSenderId: '184071946564',
    projectId: 'sipeka-8c37a',
    storageBucket: 'sipeka-8c37a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERBimeKAN6EU_kqrQloByqAyxvzEv1Ko',
    appId: '1:857519225400:ios:081aa40f4f965a877844cd',
    messagingSenderId: '857519225400',
    projectId: 'sipeka-2d426',
    storageBucket: 'sipeka-2d426.firebasestorage.app',
    iosClientId: '857519225400-d1o28d9q9bllfek0msjvpljht9ksjdsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipeka',
  );
}